config/routes.rb
Rails.application.routes.draw do
  delete 'products/:id', to:'products#destroy'
  devise_for :users
  resources :line_items
  resources :carts
  root "dashboard#index"
  resources :products do
    member do
      get :new_movement
      post :create_movement
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :reference, presence: true
    has_many :movements
  
    def quantity
      total = 0
      self.movements.each do |movement|
        if movement.movement_type == Movement::MovementTypes[:add]
          total += movement.quantity
        else
          total -= movement.quantity
        end
      end
      return total
    end
  end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="Listado de productos.xlsx"'
      }
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: 'Se ha creado el producto correctamente.'
    else
      flash[:notice] = 'Ha ocurrido un error al crear el producto.'
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @product = Product.find(params[:id])
    respond_to do |format|
      format.html
      format.xlsx {
        response.headers['Content-Disposition'] = "attachment; filename=\"Listado de movimientos - #{@product.id}.xlsx\""
      }
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to @product, notice: 'Se actualizó el producto correctamente'
    else
      render :edit
    end
  end


  def new_movement
    @product = Product.find(params[:id])
    @movement = Movement.new(product_id: @product.id)
  end

  def create_movement
    @product = Product.find(params[:id])
    @movement = Movement.new(movement_params)
    @movement.product_id = @product.id
    if @movement.save
      redirect_to @product, notice: 'Se creó el movimiento correctamente'
    else
      flash[:notice] = 'Ha ocurrido un error al crear el movimiento.'
      render :new_movement, status: :unprocessable_entity
    end
  end

  def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to @product, notice: 'Se elimino el producto correctamente', status: :see_other

  end


  private
  def product_params
    params.require(:product).permit(:name, :description, :reference)
  end

  def movement_params
    params.require(:movement).permit(:movement_type, :quantity, :comment)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="card p-5">
      
        <%= form_with(model: product) do |form| %>
          <% if product.errors.any? %>
            <div style="color: red">
              <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
        
              <ul>
                <% product.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= form.label :name, style: "display: block" %>
            <%= form.text_field :name, class:'form-control', placeholder: 'Nombre' %>
          </div>

          <div class="form-group">
            <%= form.label :reference, style: "display: block" %>
            <%= form.text_field :reference, class:'form-control', placeholder: 'Codigo de referencia SKU' %>
          </div>

          <div class="form-group">
            <%= form.label :brand, style: "display: block" %>
            <%= form.text_field :brand, class:'form-control', placeholder: 'Marca' %> 
          </div>

          <div class="form-group">
            <%= form.label :description, style: "display: block" %>
            <%= form.text_area :description, class:'form-control', placeholder: 'Descripción' %>
          </div>
                <br><br>    
          <div>
            <%= form.submit "Enviar", class:'btn btn-primary'%>
          </div>
      <% end %>
    </div>
  </div>
 
</div>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Reference:</strong>
    <%= product.reference %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= product.brand %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editar producto</h1>

<%= render "form", product: @product %>

<div>
  <%= link_to "Mostrar producto", @product, class:'btn btn-primary' %> 
   <%= link_to "Volver a productos", products_path, class:'btn btn-primary' %>
</div>

app/views/products/index.html.erb
<h1>Listado de productos</h1>
<a href="<%= new_product_path %>" class="btn btn-primary btn-icon-split">
  <span class="icon text-white-50">
      <i class="fas fa-flag"></i>
  </span>
  <span class="text">Crear Producto</span>
</a>
<a href="<%= products_path(format: :xlsx) %>" class="btn btn-success btn-icon-split">
  <span class="icon text-white-50">
      <i class="fas fa-file"></i>
  </span>
  <span class="text">Exportar a Excel</span>
</a>
<br><br>
<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Nombre</th>
      <th>Referencia</th>
      <th>Cantidad</th>
      <th>Acciones</th>
  </thead>
  <tbody>
    <% @products.each do |product| %>
    <tr>
      <td><%= product.id %></td>
      <td><%= product.name %></td>
      <td><%= product.reference %></td>
      <td><%= product.quantity %></td>
      <td><%= link_to "Detalles", product_path(product), class: 'btn btn-primary' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<h1>Crear producto</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Volver a productos", products_path, class:'btn btn-primary' %>
</div>

app/views/products/new_movement.html.erb
<h1>Crear movimiento</h1>
<div class = "row">
    <div class = "col-lg-12">
        <div class = "card">
            <table class = "table">
                <tr>
                    <td><b>Nombre:</b></td>
                    <td><%= @product.name %></td>
                </tr>    
                <tr>
                    <td><b>Referencia:</b></td>
                    <td><%= @product.reference %></td>
                </tr>
            </table>
        </div>
    </div>
</div>

<div class = "row mt-5">
    <div class = "col-lg-12">
        <div class = "card p-5">
            <%= form_with model: @movement, url: create_movement_product_path(@product) do |f| %>

                <% if @movement.errors.any? %>
                  <div class="alert alert-danger">
                    <h3><% flash [:notice] %></h3>
                    <ul>
                        <% @movement.errors.full_messages.each do |message| %>
                            <li><%= message %></li>
                        <% end %>
                    </ul>
                  </div>
                <% end %>
            
            <div class="form-group">
                <%= f.label :movement_type, "Tipo de movimiento" %>
                <%= f.select :movement_type, options_for_select(Movement.get_movement_types),{}, {class:'form-control'} %>
            </div>

            <div class = "form-group">
                <%= f.label :quantity, "Cantidad" %>
                <%= f.number_field :quantity, {class: 'form-control'} %>
            </div>

            <div class = "form-group">
                <%= f.label :comment, "Comentario" %>
                <%= f.text_area :comment, class: 'form-control' %>
            </div>
            <div class = "form-group">
                <%= f.submit 'Crear movimiento', class: 'btn btn-primary' %>
                <%= link_to 'Cancelar', product_path(@product), class: 'btn btn-danger' %>
            </div>
        <%end%>
    </div>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Detalles del producto</h1>
    <%= link_to "Regresar al listado de productos", products_path, class: 'btn btn-primary' %>
    <%= link_to "Editar", edit_product_path(@product), class: 'btn btn-primary' %>
    <%= link_to "Crear movimiento", new_movement_product_path(@product), class: 'btn btn-primary' %>
    <%= link_to "Descargar movimientos", product_path(@product, format: :xlsx), class: 'btn btn-success' %>
    <%= link_to "Eliminar producto", product_path(@product, data: {turbo_method: :delete, turbo_confirm: '¿Estas seguro?'}), class: 'btn btn-danger' %>
    <div class="card" style="padding: 20px;">
      <table class="table">
        <tr>
          <td><b>Nombre del producto:</b></td>
          <td><%= @product.name %></td>
        </tr>
        <tr>
          <td><b>Referencia:</b></td>
          <td><%= @product.reference %></td>
        </tr>
        <tr>
          <td><b>Cantidad actual:</b></td>
          <td><%= @product.quantity %></td>
        </tr>
        <tr>
          <td><b>Descripción:</b></td>
          <td><%= @product.description %></td>
        </tr>
        <tr>
          <td><b>Fecha de creación:</b></td>
          <td><%= @product.created_at %></td>
        </tr>
        <tr>
          <td><b>Fecha de actualización:</b></td>
          <td><%= @product.updated_at %></td>
        </tr>
      </table>
    </div>
  </div>
</div>
<br>
<div class="row" style="margin-top: 20px">
  <div class="col-lg-12">
    <div class="card" style="padding: 20px; ">
      <h1>Movimientos</h1>
      <table class="table">
        <thead>
          <tr>
            <th>Tipo</th>
            <th>Cantidad</th>
            <th>Comentario</th>
            <th>Fecha</th>
          </tr>
        </thead>
        <tbody>
          <% @product.movements.each do |movement| %>
          <tr>
            <td><%= movement.movement_type_name %></td>
            <td><%= movement.quantity %></td>
            <td><%= movement.comment %></td>
            <td><%= movement.created_at %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>